version: 0.0
os: linux
files:
  - source: docker-compose.yml
    destination: /opt/myapp
  - source: scripts
    destination: /opt/myapp
  - source: php
    destination: /opt/myapp
  - source: node
    destination: /opt/myapp
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
