version: 0.0
os: linux
files:
  - source: scripts/
    destination: /opt/scripts/
  - source: docker-compose.yml
    destination: /opt/docker-compose.yml
  - source: php/
    destination: /opt/php/
  - source: node/
    destination: /opt/node/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
