version: 0.0
os: linux
hooks:
files:
  - source: /
    destination: /opt
BeforeInstall:
  - location: scripts/install_dependencies
    timeout: 300
    runas: root
  - location: scripts/start_server
    timeout: 300
    runas: root
 ApplicationStop:
   - location: scripts/stop_server
    timeout: 300
    runas: root


