version: 0.0
os: linux
files:
  - source: /
    destination: /opt/application
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
      cwd: /opt/application/scripts
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
      cwd: /opt/application/scripts


