version: '3.1'

services:

  backend-node-app:
    build: ./node
    networks:
      - net
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database-mysql

  php-app:
    build: ./php
    networks:
      - net
    restart: always
    ports:
      - "80:80"

  database-mysql:
    image: mysql:8.0.28
    networks:
      - net
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'super-app'
    restart: always
    ports:
      - "3306:3306"

networks:
  net:
    driver: bridge
