#!/bin/bash

# Update your packages
echo "Updating packages..."
sudo yum update -y

# Install Docker from Amazon's repository
echo "Installing Docker..."
sudo yum install docker -y

# Start the Docker service
echo "Starting Docker..."
sudo systemctl start docker

# Enable Docker to start on boot
echo "Enabling Docker to start on boot..."
sudo systemctl enable docker

echo "Docker installed and running."
