#!/bin/bash

echo "Starting server..."
pwd   # Output the current working directory
ls -l  # List files in the current directory for verification
cd .. 
echo "Starting server..."
pwd   # Output the current working directory
ls -l  # List files in the current directory for verification
docker compose -f docker-compose.yml up -d

cd .. 
echo "Starting server..."
pwd   # Output the current working directory
ls -l  # List files in the current directory for verification
